// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/second-life-storefront/Storefront.tsx": () => import("../components/mockups/second-life-storefront/Storefront.tsx")
};
